import {
  LayoutDashboard,
  Users,
  UtensilsCrossed,
  CalendarDays,
  Receipt,
  MapPin,
  BarChart3,
  Package,
  DollarSign,
  Megaphone,
  TrendingUp,
  Shield,
  GitBranch,
  ClipboardList,
  Settings,
  User,
  History,
} from 'lucide-react'

export interface NavItem {
  label: string
  href: string
  icon: React.ElementType
}

export const CUSTOMER_NAV: NavItem[] = [
  { label: 'Profile', href: '/customer/profile', icon: User },
  { label: 'My Reservations', href: '/customer/reservations', icon: CalendarDays },
  { label: 'Order History', href: '/customer/orders', icon: History },
  { label: 'Settings', href: '/customer/settings', icon: Settings },
]

export const WAITER_NAV: NavItem[] = [
  { label: 'Live Orders', href: '/waiter/orders/live', icon: UtensilsCrossed },
  { label: 'Ready Orders', href: '/waiter/orders/ready', icon: ClipboardList },
  { label: 'Payments', href: '/waiter/payments', icon: DollarSign },
  { label: 'Receipts', href: '/waiter/receipts', icon: Receipt },
  { label: 'Floor Plan', href: '/waiter/floor-plan', icon: MapPin },
]

export const MANAGER_NAV: NavItem[] = [
  { label: 'Dashboard', href: '/branch-manager/dashboard', icon: LayoutDashboard },
  { label: 'Inventory', href: '/branch-manager/inventory', icon: Package },
  { label: 'Reservations', href: '/branch-manager/reservations', icon: CalendarDays },
  { label: 'Sales', href: '/branch-manager/sales', icon: TrendingUp },
  { label: 'Staff', href: '/branch-manager/staff', icon: Users },
  { label: 'Floor Plan', href: '/branch-manager/floor-plan', icon: MapPin },
]

export const HQ_NAV: NavItem[] = [
  { label: 'Branch Analytics', href: '/hq/analytics', icon: BarChart3 },
  { label: 'Inventory Analytics', href: '/hq/inventory', icon: Package },
  { label: 'Payroll', href: '/hq/payroll', icon: DollarSign },
  { label: 'Marketing', href: '/hq/marketing', icon: Megaphone },
  { label: 'Revenue Reports', href: '/hq/revenue', icon: TrendingUp },
]

export const ADMIN_NAV: NavItem[] = [
  { label: 'Dashboard', href: '/admin/dashboard', icon: LayoutDashboard },
  { label: 'User Management', href: '/admin/users', icon: Users },
  { label: 'Role Management', href: '/admin/roles', icon: Shield },
  { label: 'Branch Management', href: '/admin/branches', icon: GitBranch },
  { label: 'Settings', href: '/admin/settings', icon: Settings },
  { label: 'Audit Logs', href: '/admin/audit-logs', icon: ClipboardList },
]

export const PUBLIC_NAV = [
  { label: 'Home', href: '/' },
  { label: 'Menu', href: '/menu' },
  { label: 'Branches', href: '/branches' },
  { label: 'Reservations', href: '/reservations' },
  { label: 'About', href: '/about' },
  { label: 'Contact', href: '/contact' },
]

export const MENU_CATEGORIES = [
  { value: 'all', label: 'All' },
  { value: 'STARTERS', label: 'Starters' },
  { value: 'STEAKS', label: 'Steaks' },
  { value: 'MAINS', label: 'Mains' },
  { value: 'DESSERTS', label: 'Desserts' },
  { value: 'DRINKS', label: 'Drinks' },
] as const

const UNS = (id: string) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=600&h=400&q=80`

export const STATIC_MENU_ITEMS = [
  // ── Starters ──────────────────────────────────────────────────────────
  {
    id: 's1',
    name: 'Garlic Bread',
    description: 'Toasted sourdough with roasted garlic butter and fresh herbs, served with balsamic dip',
    price: 5.95,
    category: 'STARTERS' as const,
    allergens: ['gluten', 'dairy'],
    isAvailable: true,
    imageUrl: UNS('1536782376-1f22b3caa94d'),
  },
  {
    id: 's2',
    name: 'Loaded Fries',
    description: 'Crispy triple-cooked fries topped with mature cheddar sauce, smoked bacon and spring onions',
    price: 7.95,
    category: 'STARTERS' as const,
    allergens: ['dairy'],
    isAvailable: true,
    imageUrl: UNS('1573080496219-bb964701c075'),
  },
  {
    id: 's3',
    name: 'Chicken Wings',
    description: 'Crispy buffalo wings glazed in our signature hot sauce, with blue cheese dip and celery',
    price: 9.95,
    category: 'STARTERS' as const,
    allergens: ['dairy'],
    isAvailable: true,
    imageUrl: UNS('1527477396000-e27163b481c2'),
  },
  {
    id: 's4',
    name: 'Prawn Cocktail',
    description: 'Plump king prawns in Marie Rose sauce on crisp cos lettuce with brown bread',
    price: 8.95,
    category: 'STARTERS' as const,
    allergens: ['shellfish', 'gluten'],
    isAvailable: true,
    imageUrl: UNS('1565958011703-44f9829ba187'),
  },
  {
    id: 's5',
    name: 'Soup of the Day',
    description: 'Freshly made seasonal soup from our kitchen, served with crusty artisan bread and butter',
    price: 6.95,
    category: 'STARTERS' as const,
    allergens: ['gluten', 'dairy'],
    isAvailable: true,
    imageUrl: UNS('1603105037880-880cd4edfb0d'),
  },
  // ── Steaks ────────────────────────────────────────────────────────────
  {
    id: 'st1',
    name: 'Sirloin Steak',
    description: '8oz prime sirloin, dry-aged 28 days, served with your choice of sauce and triple-cooked chips',
    price: 28.95,
    category: 'STEAKS' as const,
    allergens: [],
    cookingOptions: ['Rare', 'Medium Rare', 'Medium', 'Well Done'],
    isAvailable: true,
    featured: true,
    imageUrl: UNS('1546964124-0cce460d38f9'),
  },
  {
    id: 'st2',
    name: 'Ribeye Steak',
    description: '10oz marbled ribeye, rich in deep flavour with perfect fat distribution, flame-grilled to order',
    price: 34.95,
    category: 'STEAKS' as const,
    allergens: [],
    cookingOptions: ['Rare', 'Medium Rare', 'Medium', 'Well Done'],
    isAvailable: true,
    featured: true,
    imageUrl: UNS('1529692236671-f1f6cf9683ba'),
  },
  {
    id: 'st3',
    name: 'T-Bone Steak',
    description: '16oz classic T-bone — two steaks in one, sirloin and fillet separated by the bone',
    price: 42.95,
    category: 'STEAKS' as const,
    allergens: [],
    cookingOptions: ['Rare', 'Medium Rare', 'Medium', 'Well Done'],
    isAvailable: true,
    imageUrl: UNS('1558030137-a56c1b003b68'),
  },
  {
    id: 'st4',
    name: 'Tomahawk Steak',
    description: '32oz bone-in ribeye with a full French-trimmed rib handle — the ultimate sharing centrepiece',
    price: 79.95,
    category: 'STEAKS' as const,
    allergens: [],
    cookingOptions: ['Rare', 'Medium Rare', 'Medium', 'Well Done'],
    isAvailable: true,
    featured: true,
    imageUrl: UNS('1544025162-d76694265947'),
  },
  {
    id: 'st5',
    name: 'Fillet Steak',
    description: '6oz supremely tender prime fillet — the most prized cut, lean and buttery soft',
    price: 38.95,
    category: 'STEAKS' as const,
    allergens: [],
    cookingOptions: ['Rare', 'Medium Rare', 'Medium', 'Well Done'],
    isAvailable: true,
    imageUrl: UNS('1600891964092-4316c288032e'),
  },
  // ── Mains ─────────────────────────────────────────────────────────────
  {
    id: 'm1',
    name: 'Lamb Chops',
    description: 'Herb-crusted rack of lamb with roasted root vegetables and rosemary jus',
    price: 24.95,
    category: 'MAINS' as const,
    allergens: [],
    isAvailable: true,
    imageUrl: UNS('1432139509613-5c4255815697'),
  },
  {
    id: 'm2',
    name: 'Chicken Alfredo',
    description: 'Chargrilled chicken breast over silky tagliatelle in a truffle cream sauce with aged parmesan',
    price: 16.95,
    category: 'MAINS' as const,
    allergens: ['gluten', 'dairy'],
    isAvailable: true,
    imageUrl: UNS('1555949258-eb67b1ef0ceb'),
  },
  {
    id: 'm3',
    name: 'Beef Burger',
    description: 'Hand-pressed 6oz dry-aged beef patty in a brioche bun with smoked streaky bacon and fries',
    price: 14.95,
    category: 'MAINS' as const,
    allergens: ['gluten', 'dairy'],
    isAvailable: true,
    imageUrl: UNS('1550547660-d9450f859349'),
  },
  {
    id: 'm4',
    name: 'Fish and Chips',
    description: 'Beer-battered North Sea cod with triple-cooked chips, mushy peas and tartare sauce',
    price: 15.95,
    category: 'MAINS' as const,
    allergens: ['gluten', 'fish'],
    isAvailable: true,
    imageUrl: UNS('1571167530149-c8ffe52d2a66'),
  },
  {
    id: 'm5',
    name: 'Grilled Chicken',
    description: 'Free-range chicken supreme with wild mushroom and tarragon cream sauce, served with seasonal greens',
    price: 18.95,
    category: 'MAINS' as const,
    allergens: ['dairy'],
    isAvailable: true,
    imageUrl: UNS('1598103442097-8b74394b95c7'),
  },
  // ── Desserts ──────────────────────────────────────────────────────────
  {
    id: 'd1',
    name: 'Chocolate Lava Cake',
    description: 'Warm dark Valrhona chocolate fondant with a molten centre, served with vanilla bean ice cream',
    price: 7.95,
    category: 'DESSERTS' as const,
    allergens: ['gluten', 'dairy', 'eggs'],
    isAvailable: true,
    imageUrl: UNS('1606313564200-e75d5e30476c'),
  },
  {
    id: 'd2',
    name: 'Cheesecake',
    description: 'New York style baked vanilla cheesecake on a buttery digestive base with seasonal berry compote',
    price: 6.95,
    category: 'DESSERTS' as const,
    allergens: ['dairy', 'gluten', 'eggs'],
    isAvailable: true,
    imageUrl: UNS('1567171466814-4ede929d43ab'),
  },
  {
    id: 'd3',
    name: 'Sticky Toffee Pudding',
    description: 'Classic British steamed pudding with warm butterscotch sauce and clotted cream',
    price: 7.95,
    category: 'DESSERTS' as const,
    allergens: ['gluten', 'dairy', 'eggs'],
    isAvailable: true,
    imageUrl: UNS('1551024601-bec78aea704b'),
  },
  {
    id: 'd4',
    name: 'Ice Cream Selection',
    description: 'Three generous scoops of artisan ice cream — ask your server for today\'s flavours',
    price: 5.95,
    category: 'DESSERTS' as const,
    allergens: ['dairy'],
    isAvailable: true,
    imageUrl: UNS('1580915411954-a4f7efa3e7d5'),
  },
  {
    id: 'd5',
    name: 'Apple Crumble',
    description: 'Spiced Bramley apple crumble with a golden oat topping, served with homemade custard or ice cream',
    price: 6.95,
    category: 'DESSERTS' as const,
    allergens: ['gluten', 'dairy'],
    isAvailable: true,
    imageUrl: UNS('1515467837915-15c4777cd6b0'),
  },
  // ── Drinks ────────────────────────────────────────────────────────────
  {
    id: 'dr1',
    name: 'Soft Drinks',
    description: 'Coca-Cola, Diet Coke, Lemonade, J2O, Fever-Tree tonics and mixers — all served over ice',
    price: 2.95,
    category: 'DRINKS' as const,
    allergens: [],
    isAvailable: true,
    imageUrl: UNS('1543253687-c931c8e01820'),
  },
  {
    id: 'dr2',
    name: 'Coffee',
    description: 'Espresso, Americano, Cappuccino, Flat White, Latte — all crafted with single-origin Arabica beans',
    price: 3.50,
    category: 'DRINKS' as const,
    allergens: ['dairy'],
    isAvailable: true,
    imageUrl: UNS('1495474472287-4d71bcdd2085'),
  },
  {
    id: 'dr3',
    name: 'Tea',
    description: 'English Breakfast, Earl Grey, Green Tea and herbal selection — served in a proper pot',
    price: 2.50,
    category: 'DRINKS' as const,
    allergens: [],
    isAvailable: true,
    imageUrl: UNS('1544787219-7f47ccb76574'),
  },
  {
    id: 'dr4',
    name: 'Mocktails',
    description: 'Virgin Mojito, Strawberry Daiquiri, Passion Fruit Spritz, Shirley Temple — all alcohol-free',
    price: 5.95,
    category: 'DRINKS' as const,
    allergens: [],
    isAvailable: true,
    imageUrl: UNS('1513558161293-cdaf765ed2fd'),
  },
  {
    id: 'dr5',
    name: 'Milkshakes',
    description: 'Thick and creamy hand-blended milkshakes — Chocolate, Strawberry, Vanilla, Salted Caramel',
    price: 4.95,
    category: 'DRINKS' as const,
    allergens: ['dairy'],
    isAvailable: true,
    imageUrl: UNS('1568901346375-23c9450c58cd'),
  },
]

export const STATIC_BRANCHES = [
  {
    id: 'b1',
    name: 'STEAKZ Mayfair',
    address: '12 Berkeley Square',
    city: 'London',
    postcode: 'W1J 6EQ',
    phone: '020 7946 0001',
    email: 'mayfair@steakz.co.uk',
    isActive: true,
    description: 'Our flagship London location in the heart of Mayfair',
    managerEmail: 'manager.london@steakz.co.uk',
    waiterEmail: 'waiter.london@steakz.co.uk',
  },
  {
    id: 'b2',
    name: 'STEAKZ Manchester',
    address: '45 King Street West',
    city: 'Manchester',
    postcode: 'M3 2WY',
    phone: '0161 946 0002',
    email: 'manchester@steakz.co.uk',
    isActive: true,
    description: 'Bringing the STEAKZ experience to the North',
    managerEmail: 'manager.manchester@steakz.co.uk',
    waiterEmail: 'waiter.manchester@steakz.co.uk',
  },
  {
    id: 'b3',
    name: 'STEAKZ Leeds',
    address: '27 Park Row',
    city: 'Leeds',
    postcode: 'LS1 5JD',
    phone: '0113 946 0003',
    email: 'leeds@steakz.co.uk',
    isActive: true,
    description: 'Fine dining in the heart of Yorkshire',
    managerEmail: 'manager.leeds@steakz.co.uk',
    waiterEmail: 'waiter.leeds@steakz.co.uk',
  },
  {
    id: 'b4',
    name: 'STEAKZ Birmingham',
    address: '22 Brindleyplace',
    city: 'Birmingham',
    postcode: 'B1 2LP',
    phone: '0121 946 0004',
    email: 'birmingham@steakz.co.uk',
    isActive: true,
    description: 'Premium steaks in Birmingham\'s vibrant city centre',
    managerEmail: 'manager.birmingham@steakz.co.uk',
    waiterEmail: 'waiter.birmingham@steakz.co.uk',
  },
  {
    id: 'b5',
    name: 'STEAKZ Liverpool',
    address: 'Liverpool ONE',
    city: 'Liverpool',
    postcode: 'L1 8LW',
    phone: '0151 946 0005',
    email: 'liverpool@steakz.co.uk',
    isActive: true,
    description: 'Luxury dining at the heart of Liverpool ONE',
    managerEmail: 'manager.liverpool@steakz.co.uk',
    waiterEmail: 'waiter.liverpool@steakz.co.uk',
  },
]

export const STATIC_TABLES = Array.from({ length: 16 }, (_, i) => ({
  id: `t${i + 1}`,
  number: i + 1,
  branchId: 'b1',
  capacity: i % 4 === 3 ? 6 : i % 3 === 0 ? 4 : 2,
  status: (['AVAILABLE', 'OCCUPIED', 'RESERVED', 'PAYMENT_PENDING', 'AVAILABLE', 'AVAILABLE'] as const)[i % 6],
  x: (i % 4) * 140 + 40,
  y: Math.floor(i / 4) * 120 + 40,
  shape: (i % 3 === 0 ? 'round' : 'rectangle') as 'round' | 'rectangle',
}))
